### ISSUE TITLE
Bug in provider for TourConstraintFactory

### ISSUE THREAD

**Issue by sebhoerl** [matsim-eth/discrete-mode-choice#34]
in `names.size() == 0`

**Comment by balacmi** [comment]
Where is this exactly?

**Comment by sebhoerl** [comment]
In `ConstraintModule` ... if no constraints are given (empty list / string) the `if` want to select "one" constraint... obviously this whole `if` is unnecessary.

**Comment by sebhoerl** [comment]
It doesn't change anything for existing simulations... we probably never ran anything without any constraint, because then the iteratur.next() would have produced an error.

**Comment by balacmi** [comment]
Yup 😊 good
