### ISSUE TITLE
CarModeAvailability expects to have "no"/"yes" for License

### ISSUE THREAD

**Issue by balacmi** [matsim-eth/discrete-mode-choice#39]
However, sometimes this is true or false. Especially look at PlanBuilder from the test package where it is expected in the true/false form. We should find some consistency here.

**Comment by sebhoerl** [comment]
I see, is the PlanBuilder method use anywhere? We can also just remove it. MATSim/SubtourModeChoice tests for "yes" / "no", hence the impementation in CarModeAvailability... but we could also add other cases that cover true/false... and then we probably would also want to check for Boolean vs String data type

**Comment by sebhoerl** [comment]
and in general, we could probably rename this to "CarOwnershipAndLicenseModeAvailability" or something like that

**Comment by sebhoerl** [comment]
It will be called `StandardModeAvailability` and `DefaultModeAvailability` will be renamed to `AnyModeAvailabiliy`. I change the `PlanBuilder` to reflect the standard expected attributes for "license" by MATSim, which is a string "yes" / "no".

**Comment by sebhoerl** [comment]
To make it easier: Names will stay as they are, but PlanBuilder will be adjusted. I will open another issue to make configuration of mode avialability mode flexible and easy in general.
