### ISSUE TITLE
DCM does not allow to add ReRoute as a strategy

### ISSUE THREAD

**Issue by balacmi** [matsim-eth/discrete-mode-choice#69]
While I agree that other strategies do not make much sense, I would argue that ReRoute should still be allowed in combination with DCM.

**Comment by sebhoerl** [comment]
But why does it not allow?

**Comment by balacmi** [comment]
It is disallowed here:
https://github.com/matsim-eth/discrete-mode-choice/blob/5ec959cf8754ac1b6c675f82e71dbca4ddc25dc2/src/main/java/ch/ethz/matsim/discrete_mode_choice/modules/DiscreteModeChoiceConfigurator.java#L149

**Comment by sebhoerl** [comment]
Ah ok, fix it ;)

**Comment by sebhoerl** [comment]
One the other hand, there is also a config switch, you can set `enforceSinglePlan` to `false`. Maybe it would be better just to rename this, like `enforceModeChoiceInTheLoop` or something like that.

**Comment by balacmi** [comment]
But I think that single plan should still be enforced, just that some people will re-route instead of doing DCM.
