### ISSUE TITLE
Interpretation of maximum duration of activities

### ISSUE THREAD

**Issue by sebhoerl** [matsim-eth/discrete-mode-choice#73]
Currently, we have a problem when the trips are constructed from a list of elements and one of the activities only has a maximum duration. If the leg has `NaN` travel time, the departure time of the trip will become `NaN` as well, causing problems with routing.

To test:
- Set up a test case with a maximum duration activity
- Assert that the departure time of the resulting trips is not `NaN`

**Comment by balacmi** [comment]
How is this handled in "standard" MATSim?

**Comment by sebhoerl** [comment]
It is not "handled" in MATSim, but we need to reconstruct when each trip starts by going through the plan. In this process there is a bug at the moment.
