### ISSUE TITLE
Home-based tour finder and "open" activity chains

### ISSUE THREAD

**Issue by sebhoerl** [matsim-eth/discrete-mode-choice#74]
I think the acitivty-based tour finder leads to problems later in the constraints (Subtour especially) if there are open acitvity chains (i.e. no starting/ending at the same spot). Check that.

**Comment by balacmi** [comment]
What kind of problems?

**Comment by sebhoerl** [comment]
Exceptions

**Comment by sebhoerl** [comment]
Not really an issue, because `Subtour` constriant expects a plan-based model.
